package main;

public enum ProgramState {
    WEAPON_FOUND,
    ALARM_CREATED,
    KNIFE_FOUND,
    EXPLOSIVE_FOUND,
    PASSENGER_ARRESTED,
    TRAY_SCANNED,
    SCANNER_START,
    SCANNER_ACTIVATE,
    LOAD_NEXT_PASSENGER,
    BAGGAGE_ON_ROLLER,
    BAGGAGE_TAKEN,
    AFTER_KNIFE_SCANNED,
    WEAPON_TAKEN,
    SWIPED,
    EXPLOSIVE_DESTROYED,
    SCANNER_SHUTDOWN
}
